servicemesher/envoy

start/start.md
refer to issue #127
start.md翻译全页完成
please review @rootsongjc 
thinks
=> Issue#127 translate start

operations/stats_overview.md
=> 2018-05-17 operations/stats_overview translation

configuration/health_checkers/redis.md
=> Translation completed configuration/health_checkers/redis.md

start/distro/ambassador.md
=> 翻译的文档的 Issue 编号是：#121

intro/arch_overview/access_logging.md
=> intro/arch_overview/access_logging.md #71

install/building.md
=> 翻译的文档的 Issue 编号是：#64

install/install.md
=> #65,install/install.md

operations/admin.md
=> #113 Added operations/admin.md

faq/sni.md
=> #61,faq/SNI

intro/arch_overview/tcp_proxy.md
=> #99,intro/arch_overview/tcp_proxy.md

intro/arch_overview/mongo.md
=> intro/arch_overview/mongo.md #90

operations/traffic_capture.md
=> traffic capture

intro/arch_overview/hot_restart.md
=>  intro/arch_overview/hot_restart.md #82

install/tools/route_table_check_tool.md
=> 翻译的文档的 Issue 编号是：#69

install/tools/config_load_check_tool.md
=> install/tools/config_load_check_tool.md #68

configuration/network_filters/rate_limit_filter.md
=> configuration/network_filters/rate_limit_filter.md #46

faq/zipkin_tracing.md
=> faq/zipkin_tracing.md #62

intro/arch_overview/redis.md
=> translate intro/arch_overview/redis.md

configuration/network_filters/tcp_proxy_filter.md
=> translate configuration/network_filters/tcp_proxy_filter.md

configuration/http_filters/buffer_filter.md
=> 20, configuration/http_filters/buffer_filter

configuration/http_filters/cors_filter.md
=> #21,configuration/http_filters/cors_filter

configuration/http_filters/dynamodb_filter.md
=> #22,configuration/http_filters/dynamodb_filter

configuration/http_filters/grpc_web_filter.md
=> #26, configuration/https_filters/grpc_web_filter

configuration/cluster_manager/cluster_circuit_breakers.md
=> #5 translate cluster_circuit_breakers.md

configuration/network_filters/echo_filter.md
=> #43, configuration/network_filters/echo_filter

configuration/http_filters/router_filter.md
=> #33 configuration/http_filters/router_filter.md

configuration/network_filters/mongo_proxy_filter.md
=> #44,configuration/network_filters/mongo_proxy_filter

configuration/network_filters/client_ssl_auth_filter.md
=> configuration-network_filters-client_ssl_auth_filter

intro/arch_overview/listener_filters.md
Revise the content: https://servicemesher.github.io/envoy/intro/arch_overview/listener_filters.html
=> intro arch_overview— listner_filters

install/tools/schema_validator_check_tool.md
=> # 70 - Chinese translation

configuration/cluster_manager/cluster_runtime.md
=> #7 translante cluster runtime

configuration/http_filters/rate_limit_filter.md
=> #32 : rate limit

configuration/network_filters/redis_proxy_filter.md
=> translate configuration/network_filters/redis_proxy_filter.md

configuration/http_filters/gzip_filter.md
翻译的文档的 Issue 编号是：#27
configuration/http_filters/gzip_filter.md
=> 翻译的文档的 Issue 编号是：#27

intro/arch_overview/circuit_breaking.md
review intro arch_overview circuit breaking
=> review intro arch_overview circuit breaking

intro/arch_overview/health_checking.md
=> issue#: 81

install/sandboxes/local_docker_build.md
=> 翻译的文档的 Issue 编号是：#67

intro/deployment_types/double_proxy.md
=> double_proxy.md

intro/deployment_types/service_to_service.md
=> service_to_service

intro/arch_overview/http_routing.md
=> review intro arch_overview http_routing

intro/arch_overview/websocket.md
=> review intro arch_overview websocket #233

configuration/access_log.md
=> #2 Added: access_log.md

intro/arch_overview/http_connection_management.md
=> fix some typo for http connection manager

configuration/http_filters/lua_filter.md
=> review configuration/http_filters/lua_filter

configuration/http_conn_man/route_matching.md
=> review configuration/http_conn_man/route_matching

intro/version_history.md
add 1.8 update 1.7
翻译的文档的 Issue 编号是：#111
=> version_history: add 1.8 and update 1.7

intro/arch_overview/service_discovery.md
根据 v1.9 最新文档修改 service discovery 部分
=> update service discovery content based on v1.9 doc

intro/deployment_types/front_proxy.md
=> Fix a typo

start/sandboxes/front_proxy.md
=> fix link in front_proxy.md

configuration/http_filters/fault_filter.md
=> correct some words
